# Customer Segmentation & RFM Revenue Optimization

### Import Libraries

In [1]:
import pandas as pd

### Load Dataset

In [2]:
df = pd.read_csv(r'C:\Users\prasa\Downloads\archive\online_retail_II.csv')

### Inspect the Dataset

In [3]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [5]:
df.shape

(1067371, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [7]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [8]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

### Check Missing Values

In [9]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

### Cleaning Dataset

#### 1. Remove Missing Customer ID's

In [10]:
df = df.dropna(subset=['Customer ID'])

In [11]:
df.shape

(824364, 8)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 824364 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      824364 non-null  object
 1   StockCode    824364 non-null  object
 2   Description  824364 non-null  object
 3   Quantity     824364 non-null  int64
 4   InvoiceDate  824364 non-null  object
 5   Price        824364 non-null  float64
 6   Customer ID  824364 non-null  float64
 7   Country      824364 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 56.6+ MB

In [13]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [14]:
print(f"Dataset Shape: {df.shape}")

Dataset Shape: (824364, 8)

### Check Duplicates

In [15]:
df.duplicated().sum()

np.int64(26479)

#### Remove duplicate records to prevent double-counting in revenue and customer analysis

In [16]:
df = df.drop_duplicates()

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
print(df.shape)

(797885, 8)

### Remove cancelled orders

In [19]:
df = df[~df['Invoice'].astype(str).str.startswith('C')]

In [20]:
df['Invoice'].astype(str).str.startswith('C').sum()

np.int64(0)

In [21]:
print(f"Dataset Shape: {df.shape}")

Dataset Shape: (779495, 8)

### Remove invalid Quantity

In [22]:
df = df[df['Quantity'] > 0]

In [23]:
(df['Quantity'] <= 0).sum()

np.int64(0)

In [24]:
print(f"Dataset Shape: {df.shape}")

Dataset Shape: (779495, 8)

### Remove invalid Price

In [25]:
df = df[df['Price'] > 0]

In [26]:
(df['Price'] <= 0).sum()

np.int64(0)

In [27]:
print(f"Dataset Shape: {df.shape}")

Dataset Shape: (779425, 8)

### Convert InvoiceDate to datetime

In [28]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [29]:
df['InvoiceDate']

0         2009-12-01 07:45:00
1         2009-12-01 07:45:00
2         2009-12-01 07:45:00
3         2009-12-01 07:45:00
4         2009-12-01 07:45:00
                  ...
1067366   2011-12-09 12:50:00
1067367   2011-12-09 12:50:00
1067368   2011-12-09 12:50:00
1067369   2011-12-09 12:50:00
1067370   2011-12-09 12:50:00
Name: InvoiceDate, Length: 779425, dtype: datetime64[ns]

In [30]:
type(df['InvoiceDate'].iloc[0])

pandas._libs.tslibs.timestamps.Timestamp

In [31]:
df = df.dropna(subset=['InvoiceDate'])

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 53.5+ MB

In [33]:
print(f"Dataset Shape: {df.shape}")

Dataset Shape: (779425, 8)

### Convert Customer ID to Integer

In [34]:
df['Customer ID'] = df['Customer ID'].astype(int)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  int64
 7   Country      779425 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 53.5+ MB

In [36]:
df['Customer ID'].head()

0    13085
1    13085
2    13085
3    13085
4    13085
Name: Customer ID, dtype: int64

### Create TotalPrice

In [37]:
df['Total Price'] = (df['Quantity'] * df['Price']).round(2)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  int64
 7   Country      779425 non-null  object
 8   Total Price  779425 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 59.5+ MB

In [39]:
df['Total Price'].head()

0     83.4
1     81.0
2     81.0
3    100.8
4     30.0
Name: Total Price, dtype: float64

In [43]:
df.rename(columns={'Total Price': 'TotalPrice'}, inplace=True)

In [44]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country', 'TotalPrice'],
      dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  int64
 7   Country      779425 non-null  object
 8   TotalPrice   779425 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 59.5+ MB

In [46]:
df.shape

(779425, 9)

In [47]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

## Exporting File

In [48]:
df.to_csv('cleaned_retail.csv', index=False)